apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-2048
  namespace: game-2048
spec:
  ingressClassName: ngrok
  rules:
    - host: mustang-master-positively.ngrok-free.app/
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: service-2048
                port:
                  number: 8080