apiVersion: v1
kind: Namespace
metadata:
  name: game-2048
spec: {}
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-2048
  labels:
    app: play-2048
    namespace: game-2048
spec:
  selector:
    matchLabels:
      app: play-2048
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: play-2048
    spec:
      containers:
        - name: 2048-game
          image: marcincuber/2048-game
          ports:
            - name: http
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: play-2048
  name: service-2048
  namespace: game-2048
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: play-2048
#  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-2048
  namespace: ngrok-ingress-controller #namespace in which ingress controller deployed has to be this.
spec:
  ingressClassName: ngrok
  rules:
    - host: mustang-master-positively.ngrok-free.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: service-2048
                port:
                  number: 80
