apiVersion: v1
kind: Service
metadata:
  labels:
    app: 2048
  name: service-2048
  namespace: game-2048
spec:
  ports:
  - port: 2000
    protocol: TCP
    targetPort: 8080
  selector:
    app: 2048
  type: NodePort
status:
  loadBalancer: {}
